const data = [
  // Shoes
  {
    id: 1,
    img: "https://images.nike.com/is/image/DotCom/CT2302_002",
    title: "Nike Air Max 270",
    star: 4.5,
    reviews: 320,
    prevPrice: 150,
    newPrice: 120,
    company: "Nike",
    color: "Black",
    category: "Sneakers",
  },
  {
    id: 2,
    img: "https://soneesports.com/cdn/shop/products/HQ6342_5_FOOTWEAR_Photography_Side_Medial_Center_View_white.jpg?v=1695036874&width=580",
    title: "Adidas Ultraboost 22",
    star: 4.7,
    reviews: 280,
    prevPrice: 180,
    newPrice: 140,
    company: "Adidas",
    color: "black",
    category: "Sneakers",
  },
  // Sandals
  {
    id: 6,
    img: "https://images.nike.com/is/image/DotCom/CJ2033_001",
    title: "Nike Benassi Slide",
    star: 4.2,
    reviews: 190,
    prevPrice: 40,
    newPrice: 30,
    company: "Nike",
    color: "Black",
    category: "Sneakers",
  },
  {
    id: 7,
    img: "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/315193d5b4c244d3972fad6700b463e7_9366/Adilette_Comfort_Slides_Pink_GW8741_06_standard.jpg",
    title: "Adidas Adilette Comfort",
    star: 4.5,
    reviews: 160,
    prevPrice: 445,
    newPrice: 335,
    company: "Adidas",
    color: "pink",
    category: "flats",
  },
  // Heels
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/61MZJ3X1suS._AC_SY625_.jpg",
    title: "Stiletto Heels",
    star: 4.8,
    reviews: 220,
    prevPrice: 400,
    newPrice: 375,
    company: "Puma",
    color: "white",
    category: "Heels",
  },
  {
    id: 17,
    img: "https://cdn.pixelbin.io/v2/black-bread-289bfa/-6ZJSm/t.resize(w:600)/clarks-product/5063090693526/665/5063090693571_2_8044.webp",
    title: "Block Heels",
    star: 4.6,
    reviews: 180,
    prevPrice: 400,
    newPrice: 370,
    company: "Adidas",
    color: "pink",
    category: "Heels",
  },
  // Flats
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/61SowIFkULL._SY625_.jpg",
    title: "Ballet Flats",
    star: 4.4,
    reviews: 140,
    prevPrice: 360,
    newPrice: 250,
    company: "Nike",
    color: "white",
    category: "Flats",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/71JOAGIbBQL._SX625_.jpg",
    title: "Loafer Flats",
    star: 4.3,
    reviews: 130,
    prevPrice: 65,
    newPrice: 55,
    company: "Puma",
    color: "brown",
    category: "Flats",
  },
  // Sneakers
  {
    id: 20,
    img: "https://images.nike.com/is/image/DotCom/DJ2739_100",
    title: "Nike Air Force 1",
    star: 4.8,
    reviews: 400,
    prevPrice: 460,
    newPrice: 340,
    company: "Nike",
    color: "White",
    category: "Sneakers",
  },
  {
    id: 21,
    img: "https://soneesports.com/cdn/shop/files/GZ9257_5_FOOTWEAR_Photography_Side_Medial_Center_View_white_a28346db-ed94-47d3-b389-3aa9e7fba174.jpg?v=1716360040&width=580",
    title: "Adidas NMD R1",
    star: 4.7,
    reviews: 370,
    prevPrice: 150,
    newPrice: 130,
    company: "Adidas",
    color: "Black",
    category: "Sneakers",
  },
    {
      id: 31,
      img: "https://i.pinimg.com/736x/ae/ca/a5/aecaa5a90abbd58d395db9da2a0535b0.jpg",
      title: "Nike Air Max Sandal",
      star: 4.5,
      reviews: 280,
      prevPrice: 480,
      newPrice: 360,
      company: "Nike",
      color: "pink",
      category: "Sandals",
    },
    {
      id: 32,
      img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/401029/01/sv01/fnd/IND/fmt/png/Softride-Pro-24-Super-PUMA-Men's-Slides",
      title: "Puma Slide Pro",
      star: 4.6,
      reviews: 320,
      prevPrice: 190,
      newPrice: 170,
      company: "Puma",
      color: "black",
      category: "Sandals",
    },
    {
      id: 33,
      img: "https://m.media-amazon.com/images/I/41A+Ye0xTdL._SY625_.jpg",
      title: "Adidas Comfort Flip",
      star: 4.7,
      reviews: 350,
      prevPrice: 200,
      newPrice: 180,
      company: "Adidas",
      color: "black",
      category: "flats",
    },
    {
      id: 34,
      img: "https://rukminim2.flixcart.com/image/832/832/xif0q/sandal/2/0/d/6-iq6661-7-reebok-collegiate-brown-boulder-beige-original-imagywnugysvwudf.jpeg?q=70&crop=false",
      title: "Puma Chill Sandal",
      star: 4.4,
      reviews: 260,
      prevPrice: 400,
      newPrice: 350,
      company: "Puma",
      color: "brown",
      category: "Sandals",
    },
      {
        "id": 1,
        "img": "https://tse2.mm.bing.net/th?id=OIP._-rO9Eqxi95HDrFfKlj_fQHaFj&pid=Api",
        "title": "Betsey Johnson Mari Sandal",
        "star": 4.6,
        "reviews": 320,
        "prevPrice": 280,
        "newPrice": 275,
        "company": "nike",
        "color": "black",
        "category": "Sandals"
      },
      {
        "id": 2,
        "img": "https://i.pinimg.com/736x/04/66/99/046699cb5a76bb71474812546777bc84.jpg",
        "title": "Betsey Johnson Heel",
        "star": 4.8,
        "reviews": 290,
        "prevPrice": 300,
        "newPrice": 290,
        "company": "puma",
        "color": "blue",
        "category": "Heels"
      },
      {
        "id": 3,
        "img": "https://m.media-amazon.com/images/I/81RTPUF7LwL._AC_SY500_.jpg",
        "title": "Betsey Johnson Denni heeled Sandal",
        "star": 4.7,
        "reviews": 280,
        "prevPrice": 400,
        "newPrice": 380,
        "company": "adidas",
        "color": "pink",
        "category": "sandals"
      },
      {
        "id": 4,
        "img": "https://i.pinimg.com/736x/d0/8f/cc/d08fcc7512702fadb4457187db8723a1.jpg",
        "title": "Cady Ankle Bootie",
        "star": 4.5,
        "reviews": 250,
        "prevPrice": 410,
        "newPrice": 350,
        "company": "adidas",
        "color": "blue",
        "category": "Heels"
      }
  
];

export default data