export const data = [
    {
      id: 1,
      img: "https://images.nike.com/is/image/DotCom/CT2302_002",
      title: "Nike Air Max 270",
      star: 4.5,
      reviews: 320,
      prevPrice: 150,
      newPrice: 120,
      company: "Nike",
      color: "Black",
      category: "Shoes",
    },
    {
      id: 2,
      img: "https://images.adidas.com/is/image/adidas/IG7966",
      title: "Adidas Ultraboost 22",
      star: 4.7,
      reviews: 280,
      prevPrice: 180,
      newPrice: 140,
      company: "Adidas",
      color: "White",
      category: "Shoes",
    },
    {
      id: 3,
      img: "https://images.puma.com/is/image/PUMA/377592_01",
      title: "Puma RS-X",
      star: 4.6,
      reviews: 250,
      prevPrice: 140,
      newPrice: 110,
      company: "Puma",
      color: "Blue",
      category: "Shoes",
    },
    {
      id: 4,
      img: "https://images.converse.com/is/image/Converse/170112C",
      title: "Converse Chuck Taylor",
      star: 4.3,
      reviews: 300,
      prevPrice: 90,
      newPrice: 75,
      company: "Converse",
      color: "Red",
      category: "Shoes",
    },
    {
      id: 5,
      img: "https://images.reebok.com/is/image/Reebok/HR0036",
      title: "Reebok Nano X2",
      star: 4.4,
      reviews: 210,
      prevPrice: 130,
      newPrice: 100,
      company: "Reebok",
      color: "Grey",
      category: "Shoes",
    },
    {
      id: 6,
      img: "https://images.nike.com/is/image/DotCom/CJ2033_001",
      title: "Nike Benassi Slide",
      star: 4.2,
      reviews: 190,
      prevPrice: 40,
      newPrice: 30,
      company: "Nike",
      color: "Black",
      category: "Sandals",
    },
    {
      id: 7,
      img: "https://images.adidas.com/is/image/adidas/FY8963",
      title: "Adidas Adilette Comfort",
      star: 4.5,
      reviews: 160,
      prevPrice: 45,
      newPrice: 35,
      company: "Adidas",
      color: "White",
      category: "Sandals",
    },
    {
      id: 8,
      img: "https://images.reebok.com/is/image/Reebok/FY9839",
      title: "Reebok Classic Slide",
      star: 4.1,
      reviews: 140,
      prevPrice: 35,
      newPrice: 25,
      company: "Reebok",
      color: "Navy",
      category: "Sandals",
    },
    {
      id: 9,
      img: "https://images.puma.com/is/image/PUMA/372279_01",
      title: "Puma Popcat 20",
      star: 4.3,
      reviews: 180,
      prevPrice: 38,
      newPrice: 28,
      company: "Puma",
      color: "Blue",
      category: "Sandals",
    },
    {
      id: 10,
      img: "https://images.converse.com/is/image/Converse/166799C",
      title: "Converse One Star",
      star: 4.6,
      reviews: 290,
      prevPrice: 95,
      newPrice: 80,
      company: "Converse",
      color: "Green",
      category: "Shoes",
    },
    {
      id: 11,
      img: "https://images.nike.com/is/image/DotCom/DA4086_001",
      title: "Nike Air Force 1",
      star: 4.8,
      reviews: 400,
      prevPrice: 160,
      newPrice: 140,
      company: "Nike",
      color: "White",
      category: "Shoes",
    },
    {
      id: 12,
      img: "https://images.adidas.com/is/image/adidas/ID9573",
      title: "Adidas Forum Low",
      star: 4.7,
      reviews: 370,
      prevPrice: 110,
      newPrice: 95,
      company: "Adidas",
      color: "Grey",
      category: "Shoes",
    },
    {
      id: 13,
      img: "https://images.reebok.com/is/image/Reebok/GY1080",
      title: "Reebok Club C 85",
      star: 4.5,
      reviews: 260,
      prevPrice: 100,
      newPrice: 85,
      company: "Reebok",
      color: "White",
      category: "Shoes",
    },
    {
      id: 14,
      img: "https://images.puma.com/is/image/PUMA/386385_02",
      title: "Puma Suede Classic",
      star: 4.4,
      reviews: 240,
      prevPrice: 120,
      newPrice: 100,
      company: "Puma",
      color: "Black",
      category: "Shoes",
    },
    {
      id: 15,
      img: "https://images.nike.com/is/image/DotCom/CW7588_001",
      title: "Nike Joyride Run",
      star: 4.5,
      reviews: 270,
      prevPrice: 180,
      newPrice: 150,
      company: "Nike",
      color: "Red",
      category: "Shoes",
    },
  ];
  